//Local
POST http://localhost:3000/user
content-type: application/json

{
    "username": "tstark",
    "password": "iamironman"
}
###
GET http://localhost:3000/user
###
PUT http://localhost:3000/user/62927e9c60e3cd34f0cf425e
Content-Type: application/json

{
    "username": "tstark",
    "password": "1am1ronman"
}
###
DELETE http://localhost:3000/user/62927e9c60e3cd34f0cf425e


// Heroku Deployment
###
POST https://recipe-book-cse341.herokuapp.com/user
content-type: application/json

{
    "username": "bwayne",
    "password": "iambatman"
}
###
GET https://recipe-book-cse341.herokuapp.com/user
###

PUT http://recipe-book-cse341.herokuapp.com/user/62927e9c60e3cd34f0cf425e
Content-Type: application/json

{
    "username": "tstark",
    "password": "1am1ronman"
}
###
DELETE http://recipe-book-cse341.herokuapp.com/user/62927e9c60e3cd34f0cf425e

