POST http://localhost:3000/user
content-type: application/json

{
    "username": "tstark",
    "password": "iamironman"
}
###
GET http://localhost:3000/user
###
POST https://recipe-book-cse341.herokuapp.com/user
content-type: application/json

{
    "username": "bwayne",
    "password": "iambatman"
}
###
GET https://recipe-book-cse341.herokuapp.com/user
